# Generated by Django 5.2.8 on 2026-02-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileshare',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
