# Generated by Django 5.2.8 on 2026-03-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notification_delete_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message_type',
            field=models.CharField(choices=[('USR', 'User Registration'), ('FRS', 'Friendship request sent'), ('FRA', 'Friendship request accepted'), ('FRR', 'Friendship request received'), ('OTH', 'Other')], default='OTH', max_length=3),
        ),
    ]
