# Generated by Django 5.2.8 on 2026-03-03 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_friends_friendshiprelationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendshiprelationship',
            name='reciever',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_receiver', to=settings.AUTH_USER_MODEL),
        ),
    ]
