# Generated by Django 5.2.8 on 2026-03-03 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_friendshiprelationship_reciever'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendshiprelationship',
            old_name='reciever',
            new_name='receiver',
        ),
    ]
