# Generated by Django 5.2.8 on 2026-03-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_reciever_friendshiprelationship_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendshiprelationship',
            name='is_accepted',
        ),
        migrations.AddField(
            model_name='friendshiprelationship',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='friendshiprelationship',
            constraint=models.UniqueConstraint(fields=('sender', 'receiver'), name='unique_friend_request'),
        ),
    ]
