# Generated by Django 5.2.8 on 2026-03-04 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_friendshiprelationship_is_accepted_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FriendshipRelationship',
            new_name='FriendshipRequest',
        ),
    ]
